service: cloudwatch-logs-to-metrics

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
      Resource: "*"

functions:
  custom-metrics:
    handler: cloudwatch-logs-to-metrics/handler.handler
    description: Sends async metrics from CloudWatch Logs to CloudWatch Metrics
    memorySize: 128

resources:
  Resources:
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::Join:
            - ""
            - - "Ref" : "CustomDashmetricsLambdaFunction"
        Principal: logs.#{AWS::Region}.amazonaws.com